

CREATE TABLE `inscrito` (
  `idINSCRITO` int(10) UNSIGNED NOT NULL,
  `NOME` varchar(45) NOT NULL,
  `PESO` char(10) DEFAULT NULL,
  `CPF` char(14) NOT NULL,
  `UF` varchar(45) DEFAULT NULL,
  `DATANASC` char(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



ALTER TABLE `inscrito`
  ADD PRIMARY KEY (`idINSCRITO`),
  ADD UNIQUE KEY `CPF_UNIQUE` (`CPF`);



ALTER TABLE `inscrito`
  MODIFY `idINSCRITO` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;

